### ISSUE TITLE
Improve update mechanism

### ISSUE THREAD

**Issue by jackmcconnell** [BathHacked/banes-police-crimes#1]
Instead of doing a put to replace all the data and then a push to upsert the rest every month, it should use a get request to check what the previous month's data was and try and upload the following month.

**Comment by markowen** [comment]
Upsert is what you need to use for pretty much everything, unless you're starting again from scratch. Socrata is awesome at figuring everything out for you. Doing a GET to check existence is very slow & much less efficient than using upsert.

The missing piece to the jigsaw is having an unique ID for each row. When you do an upsert, rows with the same ID are updated & rows with a fresh ID are appended. The crime ID looks like a good candidate for this. For time series data, without an ID, I usually create a hash of datetime+[a useful field to group on e.g. location].

Go to `About > Edit Metadata > API Endpoint > Row Identifier` within the dataset & choose the column to use as an ID. This is the bit that makes the magic happen.

**Comment by jackmcconnell** [comment]
Thanks Mark, 
That's really useful - i'll try that. 

The problem I was having was that using post (upsert) was just causing the data to get appended to the end of the dataset as opposed to overwriting it. 
It sound like once the initial put is done however, if I set the Row Identifier to be the Crime ID (which is unique as far as I can gather from the data.police.uk documentation) then it should stop that from happening. 

I'll let you know how I get on.
